package org.infotoast.sentimentvalue;

import java.io.FileNotFoundException;

public class SentimentValue {
    public static void main(String[] args) throws FileNotFoundException {
        Review review = new Review();
        review.doSentimentValue();
        System.out.println("Autogenerated review: " + review.fakeReview("SimpleReview.txt"));
    }
}
